-- ********************************** Eliminate Duplications ********************************** 


USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE PROJECT1;
USE SCHEMA PUBLIC;

SELECT *
FROM CUSTOMERS;

SELECT EMAIL, COUNT(ID)
FROM CUSTOMERS 
GROUP BY EMAIL;
HAVING COUNT(ID) > 1;


SELECT ID, NAME, EMAIL, LASTTRANSACTION, RANK() over (partition BY EMAIL ORDER BY to_date(LASTTRANSACTION, 'AUTO')desc) as RANK
FROM CUSTOMERS
QUALIFY RANK = 1;


