-- ********************************** Handling Missing Values ********************************** 


USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE PROJECT1;
USE SCHEMA PUBLIC;

SELECT *
FROM CUSTOMERS;

-- USING DELETION --
SELECT * 
FROM CUSTOMERS
WHERE NOT (EMAIL IS NULL OR EMAIL='');

-- USING IMPUTATION --
SELECT COMPANY, IFF(COMPANY IS NULL OR COMPANY = '', 'NA', COMPANY) as COMPANY_NAME
FROM CUSTOMERS;

